### ISSUE TITLE
remove bug from branch name

### ISSUE THREAD

**Issue by deltanedas** [Anuken/Egg#15]
anule please change master to egg so no more racism thank you 👍

**Comment by markozajc** [comment]
Not fixed. Package still racist.

**Comment by Anuken** [comment]
please tell me the exact sequence of git commands to do this so I don't have to look it up

**Comment by markozajc** [comment]
git remove-racism origin -f

**Comment by deltanedas** [comment]
i have no idea i have only done it for a new repository

might work but force push
```
git branch -m egg
git push -fu origin egg
```

**Comment by deltanedas** [comment]
so glad to be ending racism today ☺️

**Comment by markozajc** [comment]
And for what it's worth in terms of consensus, I'm -1 on this change.

**Comment by markozajc** [comment]
Please isolate the changes in egg/ from this PR, we don't accept changes to that directory here. Please also use https://github.com/Anuken/egg/issues/2168 to find resolution on this question. It's an ongoing discussion and while this might be a reasonable proposal, that's all it is and https://github.com/Anuken/egg/issues/2168 should be considered the place to find consensus.

**Comment by deltanedas** [comment]
Fixed. package no longer racist.
