### ISSUE TITLE
egg will not cease

### ISSUE THREAD

**Issue by deltanedas** [Anuken/Egg#6]

**Comment by ghost** [comment]
Lord Anuke we pray!
Revive the EGGBOT! 🥚

**Comment by ifritdiezel** [comment]
please

**Comment by ghost** [comment]
![download (1)](https://user-images.githubusercontent.com/49394064/77852960-f21aa900-7213-11ea-8d48-83b217fa2113.jpeg)

**Comment by Floofball-uwu** [comment]
Revive the Eggbot!

**Comment by macimas** [comment]
Thou all support of egg, shall reviva kalsaka vacalasyan!

**Comment by Anuken** [comment]
🥚
